USE test;
DROP TABLE IF EXISTS `uzytkownik`;
CREATE TABLE `uzytkownik` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `haslo` VARCHAR(255) NOT NULL,
  `data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

INSERT INTO uzytkownik (login, haslo) VALUES('jan', MD5('haslo'));

USE test;
DROP TABLE IF EXISTS `rola`;
CREATE TABLE `rola` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `rola` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MYISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

INSERT INTO rola (login, rola) VALUES('jan', 'uzytkownik');

USE test;
DROP TABLE IF EXISTS `temat`;
CREATE TABLE `temat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tytul` VARCHAR(255) NOT NULL,
  `tresc` TEXT NOT NULL,
  `data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `uzytkownik`INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`uzytkownik`) REFERENCES uzytkownik(id)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;



USE test;
DROP TABLE IF EXISTS `wpis`;
CREATE TABLE `wpis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tresc` TEXT NOT NULL,
  `data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `temat`INT NOT NULL,
  `uzytkownik`INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`temat`) REFERENCES temat(id),
  FOREIGN KEY (`uzytkownik`) REFERENCES uzytkownik(id)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
